version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: finance-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: finance_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
  pgvector:
      image: ankane/pgvector
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: vector_store
      ports:
        - "5432:5432"
